-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 14:04:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema localhost:3306
-- -----------------------------------------------------
-- my database- created from an ERD

-- -----------------------------------------------------
-- Schema localhost:3306
--
-- my database- created from an ERD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `localhost:3306` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `localhost:3306` ;

-- -----------------------------------------------------
-- Table `localhost:3306`.`reciepts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localhost:3306`.`reciepts` (
  `ref_no` INT NOT NULL AUTO_INCREMENT,
  `date_of_purchase` VARCHAR(45) NOT NULL,
  `total_price(PLN)` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ref_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localhost:3306`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localhost:3306`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `emp_name` VARCHAR(100) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `birth_date` VARCHAR(45) NOT NULL,
  `emp_address` VARCHAR(45) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `contact_details` INT NOT NULL,
  `reciepts_ref_no` INT NOT NULL,
  PRIMARY KEY (`idEmployee`, `reciepts_ref_no`),
  INDEX `fk_Employee_reciepts_idx` (`reciepts_ref_no` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_reciepts`
    FOREIGN KEY (`reciepts_ref_no`)
    REFERENCES `localhost:3306`.`reciepts` (`ref_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localhost:3306`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localhost:3306`.`albums` (
  `idalbums` INT NOT NULL,
  `album_name` VARCHAR(45) NOT NULL,
  `artist/band` VARCHAR(45) NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  `release_date` VARCHAR(45) NOT NULL,
  `num_of_songs` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalbums`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localhost:3306`.`Bands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localhost:3306`.`Bands` (
  `idBands` INT NOT NULL AUTO_INCREMENT,
  ` band_name` VARCHAR(45) NOT NULL,
  `num of_albums` VARCHAR(45) NOT NULL,
  `albums_idalbums` INT NOT NULL,
  PRIMARY KEY (`idBands`, `albums_idalbums`),
  INDEX `fk_Bands_albums1_idx` (`albums_idalbums` ASC) VISIBLE,
  CONSTRAINT `fk_Bands_albums1`
    FOREIGN KEY (`albums_idalbums`)
    REFERENCES `localhost:3306`.`albums` (`idalbums`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localhost:3306`.`albums_has_reciepts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localhost:3306`.`albums_has_reciepts` (
  `albums_idalbums` INT NOT NULL,
  `reciepts_ref_no` INT NOT NULL,
  PRIMARY KEY (`albums_idalbums`, `reciepts_ref_no`),
  INDEX `fk_albums_has_reciepts_reciepts1_idx` (`reciepts_ref_no` ASC) VISIBLE,
  INDEX `fk_albums_has_reciepts_albums1_idx` (`albums_idalbums` ASC) VISIBLE,
  CONSTRAINT `fk_albums_has_reciepts_albums1`
    FOREIGN KEY (`albums_idalbums`)
    REFERENCES `localhost:3306`.`albums` (`idalbums`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_has_reciepts_reciepts1`
    FOREIGN KEY (`reciepts_ref_no`)
    REFERENCES `localhost:3306`.`reciepts` (`ref_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localhost:3306`.`albums_has_reciepts1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `localhost:3306`.`albums_has_reciepts1` (
  `albums_idalbums` INT NOT NULL,
  `reciepts_ref_no` INT NOT NULL,
  PRIMARY KEY (`albums_idalbums`, `reciepts_ref_no`),
  INDEX `fk_albums_has_reciepts1_reciepts1_idx` (`reciepts_ref_no` ASC) VISIBLE,
  INDEX `fk_albums_has_reciepts1_albums1_idx` (`albums_idalbums` ASC) VISIBLE,
  CONSTRAINT `fk_albums_has_reciepts1_albums1`
    FOREIGN KEY (`albums_idalbums`)
    REFERENCES `localhost:3306`.`albums` (`idalbums`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_has_reciepts1_reciepts1`
    FOREIGN KEY (`reciepts_ref_no`)
    REFERENCES `localhost:3306`.`reciepts` (`ref_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
